Repository openshift/secrets-store-csi-driver-operator, pull requests merged in 2023-12, with the labels that each got.

#23 OCPBUGS-24312: failed to list *v1.APIServer: apiservers.config.openshift.io
  config/manifests/preview/secrets-store-csi-driver-operator.clusterserviceversion.yaml
Labels: jira/valid-reference, jira/severity-important, jira/valid-bug, docs-approved, lgtm, px-approved, approved

#27 OCPBUGS-23306: Add annotation to CSI driver Pod preventing eviction from the cluster-autoscaler
  assets/node.yaml
Labels: jira/valid-reference, jira/valid-bug, lgtm, approved

#26 OCPBUGS-25034: Move to rhel9, decouple from cli image
  .ci-operator.yaml
  Dockerfile.mustgather
  Dockerfile.openshift
  config/manifests/preview/image-references
Labels: jira/valid-reference, jira/valid-bug, lgtm, approved

#33 STOR-1688: Chore: add .snyk file to ignore false positives
  .snyk
Labels: jira/valid-reference, qe-approved, docs-approved, lgtm, px-approved, approved

#35 STOR-1590: Bump OLM metadata to 4.16
  Makefile
  README.md
  config/manifests/preview/secrets-store-csi-driver-operator.clusterserviceversion.yaml
  config/manifests/secrets-store-csi-driver-operator.package.yaml
Labels: jira/valid-reference, qe-approved, docs-approved, lgtm, px-approved, approved
